rgtravelguide/config/routes.rb
Rails.application.routes.draw do
  resources :registrationns

  get 'pages/about'

  root "destinations#index"
  resources :destinations

end

rgtravelguide/app/models/destination.rb
class Destination < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

rgtravelguide/app/models/registrationn.rb
class Registrationn < ActiveRecord::Base
end

rgtravelguide/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rgtravelguide/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :image, :title, :post, :comment, :rating)
    end
end

rgtravelguide/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

rgtravelguide/app/controllers/registrationns_controller.rb
class RegistrationnsController < ApplicationController
  before_action :set_registrationn, only: [:show, :edit, :update, :destroy]

  # GET /registrationns
  # GET /registrationns.json
  def index
    @registrationns = Registrationn.all
  end

  # GET /registrationns/1
  # GET /registrationns/1.json
  def show
  end

  # GET /registrationns/new
  def new
    @registrationn = Registrationn.new
  end

  # GET /registrationns/1/edit
  def edit
  end

  # POST /registrationns
  # POST /registrationns.json
  def create
    @registrationn = Registrationn.new(registrationn_params)

    respond_to do |format|
      if @registrationn.save
        format.html { redirect_to @registrationn, notice: 'Registrationn was successfully created.' }
        format.json { render :show, status: :created, location: @registrationn }
      else
        format.html { render :new }
        format.json { render json: @registrationn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrationns/1
  # PATCH/PUT /registrationns/1.json
  def update
    respond_to do |format|
      if @registrationn.update(registrationn_params)
        format.html { redirect_to @registrationn, notice: 'Registrationn was successfully updated.' }
        format.json { render :show, status: :ok, location: @registrationn }
      else
        format.html { render :edit }
        format.json { render json: @registrationn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrationns/1
  # DELETE /registrationns/1.json
  def destroy
    @registrationn.destroy
    respond_to do |format|
      format.html { redirect_to registrationns_url, notice: 'Registrationn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registrationn
      @registrationn = Registrationn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registrationn_params
      params.require(:registrationn).permit(:name, :age, :email, :address)
    end
end

rgtravelguide/app/helpers/application_helper.rb
module ApplicationHelper
end

rgtravelguide/app/helpers/destinations_helper.rb
module DestinationsHelper
end

rgtravelguide/app/helpers/pages_helper.rb
module PagesHelper
end

rgtravelguide/app/helpers/registrationns_helper.rb
module RegistrationnsHelper
end

rgtravelguide/app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control'%>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post, rows: "10", class:'form-control'%>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, rows: "10", class:'form-control'%>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_area :rating, rows: "10", class:'form-control'%>
  </div>
  <div class="actions row text-center">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

<javascript>
  console.log("Hey, I've created a rails app")
</javascript>

rgtravelguide/app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

rgtravelguide/app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="row text-center">Destinations</h1>
</br>
<% if @destinations.any? %>
  <% @destinations.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.compact.each do |destination| %>
        <div class="col-xs-4" style="margin-top: 20px;">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= link_to image_tag(destination.image_url, :width => '100%', :height => '200px'), destination if destination.image.present?%>
            </div>
            <div class="panel-footer">
              <h4 class="text-center"><%= link_to destination.name, destination %></h4>
              <p class="text-center"><%= destination.title %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else  %>
   <p>No destinations found.</p>
<% end %>

rgtravelguide/app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

rgtravelguide/app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="margin:auto; width: 60%">
<h1 class=" text-center" style="margin-bottom: 30px;" >
  <strong><%= @destination.name %></strong>
</h1>

<p class="text-center">
  <%= image_tag(@destination.image_url, :width => 600) if @destination.image.present? %>
</p>

<h2 class="text-center">
  <strong><%= @destination.title %></strong>
</h2>

<p style="white-space: pre-line;">
  <%= @destination.post %>
</p>

<p style="white-space: pre-line;">
  <%= @destination.comment %>
</p>
  
<br/>

<p class="text-center">
  <%= link_to 'Edit', edit_destination_path(@destination) %> |
  <%= link_to 'Delete', @destination, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to 'Back', destinations_path %>
</p>
</div>

rgtravelguide/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rgtravelguide</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "RGTravelGuide", destinations_path, class: "navbar-brand" %>
      </div>
       <p class="navbar-text navbar-right">
        <%= link_to 'About', pages_about_path, class:'navbar-link' %>
        </p>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Destinations", destinations_path %></li>
          <li><%= link_to 'Add New Destination', new_destination_path %></li>
          <li><%= link_to 'Registrations', registrationns_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted">Rails Girls KL 2017</p>
    </div>
  </footer>
</body>
</html>

rgtravelguide/app/views/pages/about.html.erb
<h1>Pages about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
    

rgtravelguide/app/views/registrationns/_form.html.erb
<%= form_for(@registrationn) do |f| %>
  <% if @registrationn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registrationn.errors.count, "error") %> prohibited this registrationn from being saved:</h2>

      <ul>
      <% @registrationn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rgtravelguide/app/views/registrationns/edit.html.erb
<h1>Editing registrationn</h1>

<%= render 'form' %>

<%= link_to 'Show', @registrationn %> |
<%= link_to 'Back', registrationns_path %>

rgtravelguide/app/views/registrationns/index.html.erb
<h1>Listing registrationns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registrationns.each do |registrationn| %>
      <tr>
        <td><%= registrationn.name %></td>
        <td><%= registrationn.age %></td>
        <td><%= registrationn.email %></td>
        <td><%= registrationn.address %></td>
        <td><%= link_to 'Show', registrationn %></td>
        <td><%= link_to 'Edit', edit_registrationn_path(registrationn) %></td>
        <td><%= link_to 'Destroy', registrationn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registrationn', new_registrationn_path, class: "btn btn-primary" %>
  
  </button>
  
</button>

rgtravelguide/app/views/registrationns/new.html.erb
<h1>New registrationn</h1>

<%= render 'form' %>

<%= link_to 'Back', registrationns_path %>

rgtravelguide/app/views/registrationns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registrationn.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @registrationn.age %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @registrationn.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @registrationn.address %>
</p>

<%= link_to 'Edit', edit_registrationn_path(@registrationn) %> |
<%= link_to 'Back', registrationns_path %>